In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("house_price.csv")

In [3]:
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [4]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [7]:
df.dtypes

date              object
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street            object
city              object
statezip          object
country           object
dtype: object

In [8]:
df=df.drop(columns=["date","country","statezip","street","city"],axis=1)

In [9]:
df["price"]=df["price"].astype(int)

In [10]:
df=df[(df["price"]>0) & (df["price"]<2000000)]

In [11]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
2,342000,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992
5,490000,2.0,1.00,880,6380,1.0,0,0,3,880,0,1938,1994
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,308166,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979
4596,534333,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009
4597,416904,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0
4598,203400,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0
4599,220600,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0

In [12]:
df.dtypes

price              int64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
dtype: object

In [13]:
X=df.drop(columns=["price"],axis=1)
y=df["price"]

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [15]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

In [16]:
lr.fit(X_train,y_train)

LinearRegression()

In [17]:
lr_pred=lr.predict(X_test)

In [18]:
print("Score of Training in LR: ",lr.score(X_train,y_train))
print("Score of Testing in LR: ",lr.score(X_test,y_test))

Score of Training in LR:  0.5506083156267337
Score of Testing in LR:  0.5364460965632645

In [19]:
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
import numpy as np

In [20]:
print("Mean Absolute error in LR: ",mae(y_test,lr_pred))
print("Mean Squared error in LR: ",mse(y_test,lr_pred))
print("Root means squared error in LR: ",np.sqrt(mse(y_test,lr_pred)))

Mean Absolute error in LR:  137941.09324156493
Mean Squared error in LR:  35330871791.15633
Root means squared error in LR:  187965.08130808853

In [21]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    random_state=42
)
rfr.fit(X_train,y_train)

RandomForestRegressor(min_samples_split=5, n_estimators=300, random_state=42)

In [22]:
rfr_pred=rfr.predict(X_test)

In [23]:
print("Score of Training in rfr: ",rfr.score(X_train,y_train))
print("Score of Testing in rfr: ",rfr.score(X_test,y_test))

Score of Training in rfr:  0.9043735719088928
Score of Testing in rfr:  0.5516027147023399

In [24]:
print("Mean Absolute error in rfr: ",mae(y_test,rfr_pred))
print("Mean Squared error in rfr: ",mse(y_test,rfr_pred))
print("Root means squared error in rfr: ",np.sqrt(mse(y_test,rfr_pred)))

Mean Absolute error in rfr:  133937.07588910236
Mean Squared error in rfr:  34175673812.476658
Root means squared error in rfr:  184866.63791089147

In [25]:
from sklearn.tree import DecisionTreeRegressor

dtr=DecisionTreeRegressor()
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [26]:
dtr_pred=dtr.predict(X_test)

In [27]:
print("Score in Training DTR:",dtr.score(X_train,y_train))
print("Score in Testing DTR: ",dtr.score(X_test,y_test))

print("Mean Absolute Error: ",mae(y_test,dtr_pred))
print("Mean Squaredd Error: ",mse(y_test,dtr_pred))
print("Root mean Squared Error: ",np.sqrt(mse(y_test,dtr_pred)))

Score in Training DTR: 0.999994872585319
Score in Testing DTR:  0.09495383392105905
Mean Absolute Error:  187416.41620421753
Mean Squaredd Error:  68980262752.0677
Root mean Squared Error:  262640.938834881

In [28]:
from sklearn.svm import SVR

svr=SVR()
svr.fit(X_train,y_train)

SVR()

In [29]:
svr_pred=svr.predict(X_test)

In [30]:
print("Score in Training SVR:",svr.score(X_train,y_train))
print("Score in Testing SVR: ",svr.score(X_test,y_test))

print("Mean Absolute Error: ",mae(y_test,svr_pred))
print("Mean Squaredd Error: ",mse(y_test,svr_pred))
print("Root mean Squared Error: ",np.sqrt(mse(y_test,svr_pred)))

Score in Training SVR: -0.056467215841515817
Score in Testing SVR:  -0.04934356083708913
Mean Absolute Error:  200361.59297344025
Mean Squaredd Error:  79978234543.91518
Root mean Squared Error:  282804.23360323865

In [37]:
len(df.columns)

57

In [34]:
print(df.iloc[12])

price            365000.0
bedrooms              3.0
bathrooms             1.0
sqft_living        1090.0
sqft_lot           6435.0
floors                1.0
waterfront            0.0
view                  0.0
condition             4.0
sqft_above         1090.0
sqft_basement         0.0
yr_built           1955.0
yr_renovated       2009.0
Name: 13, dtype: float64

In [36]:
import numpy as np

def predict_house_price(
    bedrooms=3,
    bathrooms=2,
    sqft_living=1500,
    sqft_lot=6000,
    floors=1,
    waterfront=0,
    view=0,
    condition=3,
    sqft_above=1500,
    sqft_basement=0,
    yr_built=1990,
    yr_renovated=0
):

    temp_array = [
        bedrooms,
        bathrooms,
        sqft_living,
        sqft_lot,
        floors,
        waterfront,
        view,
        condition,
        sqft_above,
        sqft_basement,
        yr_built,
        yr_renovated
    ]

    temp_array = np.array([temp_array])

    prediction = lr.predict(temp_array)

    return int(prediction[0])

In [38]:
price = predict_house_price(
    bedrooms=3,
    bathrooms=1,
    sqft_living=1090,
    sqft_lot=6005,
    floors=1,
    waterfront=0,
    view=0,
    condition=4,
    sqft_above=1090,
    sqft_basement=0,
    yr_built=1955,
    yr_renovated=2009
)

print("Predicted Price:", price)

Predicted Price: 282682

C:\Users\Tushar Kotian\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [40]:
import pickle

with open('house_price.pkl','wb') as f:
    pickle.dump(lr,f)